export const onBoarding =
  "https://cidxhvsaxjndcogbdgav.supabase.co/storage/v1/object/sign/PRAS/qubitchat/onboarding.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJQUkFTL3F1Yml0Y2hhdC9vbmJvYXJkaW5nLnBuZyIsImlhdCI6MTc0MTAyMzczMiwiZXhwIjoyMDU2MzgzNzMyfQ.BNtUyCHfV_0UdF7EQ2srESchzU5sF4mqsoJdoQdqhUw";
export const NovaAvatar =
  "https://cidxhvsaxjndcogbdgav.supabase.co/storage/v1/object/sign/PRAS/qubitchat/nova-avatar.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJQUkFTL3F1Yml0Y2hhdC9ub3ZhLWF2YXRhci5wbmciLCJpYXQiOjE3NDEwMjMzNDEsImV4cCI6MjA1NjM4MzM0MX0.3lon8FNAX8J2C2DCnuwFHmkfLByN-OSqkFl1ccc99YY";
