export const CLERKPUBKEY = process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY!;
export const STREAM_API_KEY = process.env.EXPO_PUBLIC_STREAM_API_KEY!;
export const STREAM_API_SECRET = process.env.EXPO_PUBLIC_STREAM_API_SECRET!;
